data:
  base_path: "path/to/data"
  n_snapshot: 3000
  n_samples: 125
  n_features: 952
  mode: "eval"
  output_type: "donor"
  n_outputs: 2
  start_index: "90000"
  end_index: "90020"
  random_seed: 123
  valid_size: 0.2
  num_train_samples: 10
  use_multiprocessing: "True"

model:
  hidden_sizes: [50, 50]
  activation: "Tanh"
  dropout: 0.0

training:
  epochs: 500
  lr: 0.0001
  batch_size: 128
  weight_decay: 0.001
