name: CPU Test Training

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: List files for debugging
      run: ls -r  # -R :This will print every file and folder in the runner's log

    - name: Run Training Test Case
      run: python examples/test_training.py

    - name: Run Optimization Test
      run: python examples/test_optuna.py
    
    - name: Upload All Results
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: full-evaluation-artifacts
        path: |
          logs/
          *.pdf
          *.png
